version: "3"

services:
    golang:
        build: .
        volumes:
            - ../:/go/src/catapp
        ports:
            - "8080:8080"
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
        command: sleep infinity
volumes: 
    data:
